const D = Math.PI / 180;

/* Three starting points, all checked against the same clearance rules the
   planner applies live. Coordinates are metres from the centre of the
   terrace: x runs across the long side, z runs from the back wall (-) to the
   open edge (+). */
export const PRESETS = [
  {
    name: 'A — Pool first',
    room: { w: 14, d: 9, parapetH: 1.10, floor: 'terrazzo' },
    items: [
      { key: 'stair', x: 5.0, z: 1.6 },
      { key: 'pool9', x: -3.5, z: -0.6, tone: 'blue', wood: 'black' },
      { key: 'pergola', x: -3.5, z: -0.6 },
      { key: 'backbar', x: 1.2, z: -4.25 },
      { key: 'bar36', x: 1.2, z: -2.70 },
      { key: 'stool', x: -0.20, z: -1.95 }, { key: 'stool', x: 0.55, z: -1.95 },
      { key: 'stool', x: 1.85, z: -1.95 }, { key: 'stool', x: 2.60, z: -1.95 },
      { key: 'ps5-65', x: 1.6, z: 4.27, rot: 180 * D },
      { key: 'sectional', x: 1.6, z: 1.35, tone: 'teal' },
      { key: 'beanbag', x: 0.4, z: 3.0, tone: 'rose' }, { key: 'beanbag', x: 2.6, z: 3.0, tone: 'rose' },
      { key: 'sofa3', x: -5.2, z: 3.6, rot: 180 * D, tone: 'teal' },
      { key: 'coffee', x: -5.2, z: 2.6 },
      { key: 'armchair', x: -6.3, z: 2.2, rot: 110 * D, tone: 'rose' },
      { key: 'dj', x: -6.0, z: -3.35 },
      { key: 'spk', x: -6.7, z: -2.2 }, { key: 'spk', x: 6.6, z: -2.2 },
      { key: 'cocktail', x: 6.0, z: -3.4 }, { key: 'cocktail', x: 4.2, z: -3.4 },
      { key: 'planter', x: -0.4, z: 2.4, rot: 90 * D }, { key: 'planter', x: -0.4, z: 3.7, rot: 90 * D },
      { key: 'zone', x: -3.5, z: -0.6, w: 5.8, d: 4.6, label: 'Pool' },
      { key: 'zone', x: 1.6, z: 3.0, w: 4.6, d: 3.4, label: 'PS5' },
      { key: 'zone', x: 1.2, z: -3.4, w: 4.4, d: 2.4, label: 'Bar' },
    ],
  },
  {
    name: 'B — Gaming led',
    room: { w: 14, d: 9, parapetH: 1.10, floor: 'deck' },
    items: [
      { key: 'stair', x: -5.6, z: 1.5 },
      { key: 'ledwall', x: 6.55, z: 1.0, rot: 90 * D },
      { key: 'ps5-65', x: -1.4, z: 4.25, rot: 180 * D },
      { key: 'sectional', x: -1.4, z: 1.3, tone: 'black' },
      { key: 'gchair', x: 0.7, z: 2.9, rot: 200 * D, tone: 'black' },
      { key: 'gchair', x: -3.2, z: 2.9, rot: 160 * D, tone: 'black' },
      { key: 'beanbag', x: -0.4, z: 3.1 }, { key: 'beanbag', x: -2.2, z: 3.1 },
      { key: 'arcade', x: 6.2, z: -3.3, rot: 90 * D },
      { key: 'arcade', x: 6.2, z: -1.3, rot: 90 * D },
      { key: 'foos', x: 5.0, z: 2.6, rot: 90 * D },
      { key: 'airh', x: 2.2, z: 2.55, rot: 90 * D },
      { key: 'pool8', x: 1.0, z: -2.0, tone: 'green' },
      { key: 'bar24', x: -4.6, z: -3.24 },
      { key: 'stool', x: -5.4, z: -2.44 }, { key: 'stool', x: -4.6, z: -2.44 }, { key: 'stool', x: -3.8, z: -2.44 },
      { key: 'spk', x: -6.6, z: -3.0 }, { key: 'spk', x: 6.6, z: 3.8 },
      { key: 'zone', x: -1.4, z: 3.0, w: 6.0, d: 3.6, label: 'PS5 lounge' },
      { key: 'zone', x: 5.6, z: -2.3, w: 2.2, d: 3.6, label: 'Arcade' },
    ],
  },
  {
    name: 'C — Party mode',
    room: { w: 14, d: 9, parapetH: 1.10, floor: 'tile' },
    items: [
      { key: 'stair', x: -6.0, z: -2.6 },
      { key: 'dj', x: 0, z: -3.35 },
      { key: 'ledwall', x: 4.0, z: -4.2 },
      { key: 'spk', x: -2.6, z: -3.0 }, { key: 'spk', x: 2.6, z: -3.0 },
      { key: 'bar36', x: -4.4, z: 2.70, rot: 180 * D },
      { key: 'backbar', x: -4.4, z: 4.25, rot: 180 * D },
      { key: 'stool', x: -5.9, z: 1.9 }, { key: 'stool', x: -5.1, z: 1.9 },
      { key: 'stool', x: -3.7, z: 1.9 }, { key: 'stool', x: -2.9, z: 1.9 },
      { key: 'pool8', x: 4.3, z: 2.35, tone: 'red', wood: 'black' },
      { key: 'cocktail', x: -1.4, z: 1.2 }, { key: 'cocktail', x: 0.2, z: 1.2 },
      { key: 'cocktail', x: -1.4, z: 3.2 }, { key: 'cocktail', x: 0.2, z: 3.2 },
      { key: 'sofa2', x: 2.2, z: -1.4, tone: 'rose' },
      { key: 'sofa2', x: 6.3, z: -1.5, rot: 270 * D, tone: 'rose' },
      { key: 'firepit', x: -3.0, z: -1.2 },
      { key: 'heater', x: 4.4, z: -1.6 },
      { key: 'planter', x: 6.4, z: -3.6 },
      { key: 'zone', x: -0.6, z: 2.2, w: 4.4, d: 4.0, label: 'Dance floor' },
      { key: 'zone', x: -4.4, z: 3.5, w: 4.4, d: 2.2, label: 'Bar' },
    ],
  },
];
